//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: AssemblyVersion("0.9.2.0")]
[assembly: AssemblyFileVersion("0.9.2.0")]
[assembly: AssemblyCopyright("Copyright (C) Project Extensions 2013")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyCompany("Project Extensions")]
[assembly: AssemblyProduct("Windows Azure Service Bus Wrapper modeled after the NServiceBus pattern of IHandl" +
    "eMessage<T> (Debug DB: 0)")]


